### ISSUE TITLE
need intent for element argument in array callback functions

### ISSUE THREAD

**Issue by zbeekman** [tomedunn/json-fortran-example#1]
I don’t know which compiler you are using, but with gfortran I get an error if I don’t also add the `intent(in)` argument to the `type(json_value), pointer` `element` argument. See for example https://github.com/tomedunn/json-fortran-example/blob/master/src/myType_type.f90#L202 although there is another array callback which should also be updated

**Comment by tomedunn** [comment]
@zbeekman thanks for bringing this up. I had `intent(in)` statements in an earlier commit, I'm not sure why I took them out. I think the last time I compiled it I used gfortran 5.1 but it might have been 5.2 (I haven't tried to compile it with the Intel Fortran compiler yet). I'll play with it a bit tonight. In all likelihood I'll just add the `intent(in)` statements back into the program.
